# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [ ]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [ ]:
t = torch.zeros(8, 8)
t[0] = torch.tensor([-4, -3, -2, -6, -5, -2, -3, -4])
t[1] = torch.tensor([-1, -1, -1, -1, -1, -1, -1, -1])
t[6] = torch.tensor([1, 1, 1, 1, 1, 1, 1, 1])
t[7] = torch.tensor([4, 3, 2, 6, 5, 2, 3, 4])
t

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [ ]:
a = torch.arange(2, 21, 2)
b = torch.arange(3, 22, 2)
a * b

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
a = torch.arange(1, 111)
b = a.reshape(11, 10)
b[:, :7]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [ ]:
n = int(input())
m = int(input())
a = torch.tensor([[0,1], [2,3]])
b = a.repeat(n, m)
b[:n, :m]

4
5


tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [ ]:
t = 20 * torch.rand(4, 7)
t_min = t.min()
t_max = t.max()
a = 1 / (t_max - t_min)
b = - t_min / (t_max - t_min)
t_norm = a * t + b
t_norm

tensor([[0.4988, 0.7364, 0.5856, 1.0000, 0.1016, 0.0000, 0.1229],
        [0.0164, 0.0182, 0.7047, 0.9318, 0.9893, 0.1913, 0.0302],
        [0.2529, 0.1269, 0.9683, 0.5919, 0.8056, 0.1755, 0.9139],
        [0.3231, 0.6086, 0.2675, 0.3912, 0.6686, 0.2650, 0.0347]])

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [ ]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))
ar3 = torch.max(ar1, ar2)
ar3

tensor([[ 3,  3,  8,  9,  7,  7, 10],
        [ 9,  9,  7,  1,  7, 10,  8],
        [ 8, 10,  5,  8, 10,  9,  7],
        [ 1,  5,  4, 10,  8,  7, 10]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [ ]:
t = torch.randint(0, 101, (20,))
val, ind = torch.sort(t, descending=True)
t_val = val[1]
t_ind = ind[1]
print(t)
t_val, t_ind

tensor([27,  4, 56, 90, 92, 54, 90, 43, 66, 34, 95, 37, 39, 45, 58, 67, 80, 34,
        28, 60])


(tensor(92), tensor(4))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [ ]:
a = torch.arange(1, 111)
b = a.reshape(11, 10)
b[:, :7]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [ ]:
import numpy as np

a_2d = np.array([[3, 3, 3],
                 [4, 4, 4],
                 [5, 5, 5]])

b_1d = np.array([1, 2, 3])

b_1d_reshaped = b_1d.reshape(3, 1)
b_1d_reshaped

array([[1],
       [2],
       [3]])

In [ ]:
result = a_2d - b_1d_reshaped
result

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
ind = np.where(a == b)
ind

(array([1, 3, 5, 7]),)

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [ ]:
a = torch.arange(9).view(3,3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
new_a = torch.flip(a, dims=[0, 1])
new_a

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
ind = (a >= 5) & (a <= 10)
rez = a[ind]
rez

array([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [ ]:
a = torch.arange(9).view(3,3)
a[:, [1, 2]] = a[:, [2, 1]]
a

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a = torch.randint(0, 11, (8, 10))
b = a.sum(dim=1)
ind = torch.argmin(b)
print(a)
a[ind]

tensor([[ 9, 10,  6,  6,  0,  6, 10,  4,  8,  5],
        [ 9,  8,  0,  2,  9,  0, 10,  9,  2, 10],
        [ 3,  6,  0,  8,  9,  4,  4,  7,  1,  2],
        [ 1,  9,  2,  4,  7,  2,  4,  5,  3,  9],
        [ 1,  4,  5,  7,  6,  6,  0,  6,  8,  1],
        [ 1,  2,  9,  8,  3,  9,  4,  8,  8,  8],
        [ 6,  2,  6,  5,  5,  6,  6,  2,  5,  0],
        [ 1,  3,  3,  4,  6,  8,  1,  0,  6,  9]])


tensor([1, 3, 3, 4, 6, 8, 1, 0, 6, 9])

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
a = torch.randint(0, 101, (20,))
a[a < 30] = 30
a[a > 70] = 70
a

tensor([70, 70, 36, 69, 59, 66, 70, 30, 36, 30, 40, 30, 70, 52, 30, 70, 53, 70,
        70, 30])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [ ]:
a = torch.randint(0, 11, (30,3))
b = torch.randint(0, 11, (30,3))
c = a[a > b]
c.sum()

tensor(288)

In [ ]:
print(a)
print(b)
print(c)

tensor([[ 5,  5,  2],
        [ 4,  0,  1],
        [ 8,  3,  3],
        [ 0,  7,  1],
        [ 9,  0,  2],
        [ 3, 10, 10],
        [ 5,  4,  6],
        [ 7,  8,  3],
        [ 2,  9,  5],
        [ 1,  1,  9],
        [ 7,  1,  9],
        [ 9,  9,  5],
        [ 5,  5,  8],
        [10,  0,  8],
        [ 8, 10,  9],
        [10,  7,  4],
        [ 6,  0,  0],
        [ 0,  1,  7],
        [ 5,  5,  4],
        [10,  9,  7],
        [ 0,  8,  3],
        [ 0,  2,  5],
        [10, 10,  7],
        [ 0,  8,  7],
        [ 8,  8,  0],
        [ 4,  0,  4],
        [ 8,  6,  8],
        [ 3,  6, 10],
        [10,  3,  1],
        [ 7,  8, 10]])
tensor([[10,  3, 10],
        [ 9,  6, 10],
        [10, 10,  2],
        [ 6,  4,  6],
        [ 2,  9,  3],
        [ 6,  8,  2],
        [ 0,  9, 10],
        [10,  2,  7],
        [ 9,  2,  4],
        [ 8,  9,  9],
        [ 0,  8,  3],
        [10,  1,  2],
        [ 3, 10,  8],
        [ 7,  8,  6],
        [ 8,  1,  3],
        [

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [ ]:
a = torch.randint(0, 11, (20, 20))
row_ind = torch.arange(19)
col_ind = torch.arange(1, 20)
answ = a[row_ind, col_ind]
print(a[:5, :5])
answ

tensor([[ 7,  3,  7,  1,  2],
        [ 0,  0,  6, 10,  3],
        [ 9,  6,  8,  8,  8],
        [ 9,  4,  1,  6,  0],
        [ 7,  3,  2,  1,  3]])


tensor([ 3,  6,  8,  0,  2,  3,  6,  2,  9, 10,  6,  8,  8,  0,  5,  7,  2,  5,
         0])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [ ]:
a = torch.randint(0, 11, (5, 10))
b = torch.randint(0, 11, (5, 10))
print(f'a: \n{a}')
a[a == b] *= 2
print(f'b:\n{b}')
print(f'удвоенная а: \n{a}')

a: 
tensor([[ 6,  9,  4,  8,  6,  5,  1,  8,  1,  9],
        [ 7,  7,  8,  6,  0,  8,  4,  8,  4,  2],
        [ 2,  8,  9,  8,  8,  5,  1,  2,  3,  1],
        [10,  9,  4,  2,  2,  9, 10, 10,  9, 10],
        [ 2, 10,  3,  0,  6,  2,  0,  1,  2,  9]])
b:
tensor([[ 1,  5,  4,  1,  5,  3, 10,  1,  5,  4],
        [ 3,  1,  0,  6,  6,  4, 10,  3,  3,  9],
        [ 6,  2,  6,  6,  2, 10,  6,  8,  4,  8],
        [ 6,  3,  8,  1,  5,  8,  7,  7,  5,  2],
        [ 6,  0,  2,  4,  6,  4,  5,  2,  3,  5]])
удвоенная а: 
tensor([[ 6,  9,  8,  8,  6,  5,  1,  8,  1,  9],
        [ 7,  7,  8, 12,  0,  8,  4,  8,  4,  2],
        [ 2,  8,  9,  8,  8,  5,  1,  2,  3,  1],
        [10,  9,  4,  2,  2,  9, 10, 10,  9, 10],
        [ 2, 10,  3,  0, 12,  2,  0,  1,  2,  9]])


1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [ ]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))
ar3 = torch.randint(0, 11, (4, 7))
print(f'ar1: \n{ar1}')
print(f'ar2: \n{ar2}')
print(f'ar3: \n{ar3}')
ar1[(ar1 > ar2) & (ar1 < ar3)] = 0
print(f'ar1: \n{ar1}')

ar1: 
tensor([[10,  8,  7,  8,  3,  0,  3],
        [ 0,  2,  9,  4,  1,  4,  5],
        [ 2,  5,  2,  2,  7,  1,  4],
        [ 9,  9,  6,  4,  0, 10,  8]])
ar2: 
tensor([[ 6,  5,  6,  7,  0,  3,  0],
        [ 9, 10,  3,  6,  0,  6,  5],
        [ 3,  1, 10,  0,  6,  5,  3],
        [ 7,  0,  4,  5, 10,  0,  0]])
ar3: 
tensor([[ 6,  8,  6,  6,  3, 10,  9],
        [ 2,  2,  2,  5,  0,  7,  3],
        [ 7,  3,  6,  5, 10,  8, 10],
        [ 9,  4,  1,  9,  2,  1,  4]])
ar1: 
tensor([[10,  8,  7,  8,  3,  0,  0],
        [ 0,  2,  9,  4,  1,  4,  5],
        [ 2,  5,  2,  0,  0,  1,  0],
        [ 9,  9,  6,  4,  0, 10,  8]])


1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [ ]:
ar1 = torch.randint(0, 21, (20,5))
print(ar1)
rowmax = ar1.max(dim=1).values
a = (ar1 == rowmax[:, None])
count = a.sum(dim=0)
print(a)
rez = torch.where(count >= 5)[0]
rez

tensor([[10, 12,  7,  7, 13],
        [ 2,  5, 11, 19, 12],
        [11, 17, 12,  6,  8],
        [10, 14, 19, 20,  0],
        [20, 12,  3, 16, 14],
        [ 2,  1,  8, 14, 15],
        [ 9, 16, 17, 13,  4],
        [ 2, 11,  5, 13, 14],
        [12, 18,  7,  3,  1],
        [10,  5, 10,  2,  9],
        [ 8, 17, 14, 15,  9],
        [ 5, 15,  2,  4,  6],
        [13, 17, 10, 18, 13],
        [12,  9,  6, 16,  8],
        [11,  2, 14, 18,  4],
        [ 8, 15, 14, 14,  9],
        [19,  9,  7,  9,  9],
        [ 7,  7,  5, 10, 19],
        [ 2,  2, 13, 14,  1],
        [12, 17,  3, 20, 15]])
tensor([[False, False, False, False,  True],
        [False, False, False,  True, False],
        [False,  True, False, False, False],
        [False, False, False,  True, False],
        [ True, False, False, False, False],
        [False, False, False, False,  True],
        [False, False,  True, False, False],
        [False, False, False, False,  True],
        [False,  True, False, False, Fa

tensor([1, 3])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [ ]:
ar1 = torch.rand(4, 7)
print(ar1)
val, ind = torch.max(ar1.view(-1), dim=0)
max_row = ind // 7
max_col = ind % 7
print(val)
mask = torch.zeros_like(ar1, dtype=torch.bool)
mask[max_row + 1:, max_col + 1:] = True
ar1[mask] = 0
ar1

tensor([[0.0410, 0.6223, 0.8714, 0.4209, 0.1850, 0.6325, 0.4972],
        [0.9290, 0.6354, 0.1819, 0.3228, 0.7910, 0.5755, 0.8300],
        [0.1812, 0.7561, 0.8360, 0.2802, 0.3769, 0.4547, 0.1343],
        [0.9219, 0.7538, 0.7905, 0.1181, 0.6351, 0.2918, 0.3605]])
tensor(0.9290)


tensor([[0.0410, 0.6223, 0.8714, 0.4209, 0.1850, 0.6325, 0.4972],
        [0.9290, 0.6354, 0.1819, 0.3228, 0.7910, 0.5755, 0.8300],
        [0.1812, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9219, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре.
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [ ]:
arr = torch.randint(0, 101, (20,))
print(arr)
vals, counts = arr.unique(return_counts=True)
max_count = counts.max()
modes = vals[counts == max_count]
indices_per_mode = {int(v.item()): (arr == v).nonzero(as_tuple=True)[0] for v in modes}
chosen_mode = modes.min()
chosen_indices = (arr == chosen_mode).nonzero(as_tuple=True)[0]
chosen_indices

tensor([ 9, 36, 65, 41,  0, 85, 27, 38, 11, 98, 17, 44, 65, 41,  0, 40, 62, 19,
        29, 81])


tensor([ 4, 14])

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [ ]:
import torch

n = 100000
x = 10 * torch.rand(n)
y = x * torch.sin(x)
mask = y > 0.5
counts = mask.sum()

fraction = counts / n
fraction_float = fraction.item()

print(f"{fraction_float:.4f} - часть")
print(f"{fraction_float * 100:.2f}% - процент")

0.5274 - часть
52.74% - процент


1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [ ]:
a = torch.ones(101, dtype=torch.bool)
a[0:2] = False
for p in range(2, int(101**0.5) + 1):
    if a[p]:
        a[p*p::p] = False
p = torch.nonzero(a).squeeze(1)
p

tensor([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
        67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [ ]:
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([5, 4, 3, 2, 1])

d = (a - b)**2
sum = d.sum()
euclidean_distance = torch.sqrt(sum)

print(f"a - {a}")
print(f"b - {b}")
print(f"расстояние - {euclidean_distance.item():.2f}")

a - tensor([1, 2, 3, 4, 5])
b - tensor([5, 4, 3, 2, 1])
расстояние - 6.32


1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100.
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [ ]:
a = torch.randint(0, 101, (20, 3))
len = torch.sqrt(torch.sum(a**2, dim=1))
sort = torch.argsort(len)
a_sort = a[sort]
print(f'a - \n{a}')
print(f'длины - {len}')
print(f'векторы по возрастанию длины - \n{a_sort}')

a - 
tensor([[ 36,  54,  64],
        [ 97,  89,  75],
        [ 13,  36,  98],
        [ 51,  44,  14],
        [ 77,  76,  85],
        [ 67,  32,  94],
        [ 73,  52,  56],
        [ 27,  86,  20],
        [ 81,  46,  80],
        [ 92,  59,  70],
        [ 17,  61,  96],
        [ 23,   9,  83],
        [ 38, 100,  28],
        [ 74,  11,  75],
        [ 24,  88,  29],
        [ 70,  89,  78],
        [ 83,   7,  79],
        [ 15,  60,  81],
        [ 13,  50,  99],
        [ 29,  33,  79]])
длины - tensor([ 91.1482, 151.5091, 105.2093,  68.7968, 137.5863, 119.7873, 105.6835,
         92.3309, 122.7884, 129.7883, 115.0043,  86.5968, 110.5803, 105.9339,
         95.7131, 137.4955, 114.7998, 101.9117, 111.6692,  90.3936])
векторы по возрастанию длины - 
tensor([[ 51,  44,  14],
        [ 23,   9,  83],
        [ 29,  33,  79],
        [ 36,  54,  64],
        [ 27,  86,  20],
        [ 24,  88,  29],
        [ 15,  60,  81],
        [ 13,  36,  98],
        [ 73,  52,  56],
    

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [ ]:
a = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
mask = (a[1:-1] > a[:-2]) & (a[1:-1] > a[2:])
peaks = torch.nonzero(mask, as_tuple=True)[0] + 1
peaks

tensor([2, 5])

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
import numpy as np
arr = np.random.rand(100)
print(f'исходный массив: {arr[:10]}')
target_value = 0.5
print(f'target : {target_value}')
diff = np.abs(arr - target_value)
ind = np.argmin(diff)
val = arr[ind]
print(f"близкое число: {val:.4f}")

исходный массив: [0.7966714  0.16610961 0.64895075 0.80250989 0.7670033  0.19039729
 0.44487869 0.72271485 0.88811881 0.37650307]
target : 0.5
близкое число: 0.4977


1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = torch.tensor([[-1., 2., 4.],
                  [-3., 1., 2.],
                  [-3., 0., 1.]])
B = torch.tensor([[3., -1.],
                  [2., 1.]])
C = torch.tensor([[7., 21.],
                  [11., 8.],
                  [8., 4.]])
A_inv = torch.inverse(A)
B_inv = torch.inverse(B)
X = -A_inv @ C @ B_inv
X

tensor([[ 1.0000e+00, -1.1921e-07],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [ ]:
import torch
A = torch.tensor([[3., -3., 0., 7.],
                  [2., 2., 4., 7.],
                  [1., 2., 3., 4.],
                  [5., -4., 1., 3.]])
determinant = torch.det(A)

print(f"определитель: {determinant.item():.2f}")
if determinant == 0:
    print("Система линейно зависима")
else:
    print("Система линейно независима")

определитель: 0.00
Система линейно независима


1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами.

In [ ]:
t = torch.normal(mean=0.0, std=10.0, size=(200,)).round().to(torch.int)

min_val = t.min().item()
max_val = t.max().item()

hist, bin_edges = torch.histogram(t.float(), bins=20, range=(min_val, max_val))

print("гистограмма:", hist)
print("границы бинов:", bin_edges)

гистограмма: tensor([ 4.,  2.,  4., 10., 23., 15., 26., 20., 23., 13., 18.,  7., 14.,  4.,
         7.,  1.,  4.,  2.,  2.,  1.])
границы бинов: tensor([-20.0000, -17.5000, -15.0000, -12.5000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,
         15.0000,  17.5000,  20.0000,  22.5000,  25.0000,  27.5000,  30.0000])
