#  Forward pass

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann
* https://pytorch.org/docs/stable/generated/torch.matmul.html
* https://machinelearningmastery.com/choose-an-activation-function-for-deep-learning/
* https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/
* https://kidger.site/thoughts/jaxtyping/
* https://github.com/patrick-kidger/torchtyping/tree/master

## Задачи для совместного разбора

In [ ]:
pip install torchtyping

  Attempting uninstall: typeguard
    Found existing installation: typeguard 4.4.4
    Uninstalling typeguard-4.4.4:
      Successfully uninstalled typeguard-4.4.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
inflect 7.5.0 requires typeguard>=4.0.1, but you have typeguard 2.13.3 which is incompatible.


In [ ]:
from torchtyping import TensorType, patch_typeguard
from typeguard import typechecked
import torch as th

Scalar = TensorType[()]
patch_typeguard()

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте нейрон с заданными весами `weights` и `bias`. Пропустите вектор `inputs` через нейрон и выведите результат.

In [ ]:
class Neuron:
    def __init__(self, n_features):
        self.weights = th.randn(n_features)
        self.bias = th.randn(1)
        print(self.bias, self.weights)

    def forward(self, inputs: TensorType["n_features"]) -> Scalar:
        return inputs.dot(self.weights) + self.bias

In [ ]:
import torch as th
inputs = th.tensor([1.0, 2.0, 3.0, 4.0])

In [ ]:
neuron = Neuron(4)
neuron.forward(inputs)

tensor([-0.4384]) tensor([-0.8734,  0.0820, -0.2416, -0.4198])


tensor([-3.5522])

2\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [ ]:
class ReLU:
    @typechecked
    def forward(self, inputs: TensorType) -> TensorType:
        return th.clamp(inputs, min=0)

In [ ]:
input_matrix = th.randn(4, 3)
relu_activation = ReLU()
output_matrix = relu_activation.forward(input_matrix)

print("Входная матрица:\n", input_matrix)
print("Матрица после применения ReLU:\n", output_matrix)

Входная матрица:
 tensor([[ 1.1212,  0.1854,  0.3594],
        [ 0.6683,  0.3058,  0.3114],
        [-0.0315, -0.3334,  1.7900],
        [-0.4768, -0.9121, -0.4716]])
Матрица после применения ReLU:
 tensor([[1.1212, 0.1854, 0.3594],
        [0.6683, 0.3058, 0.3114],
        [0.0000, 0.0000, 1.7900],
        [0.0000, 0.0000, 0.0000]])


3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)
где $Y_i$ - правильный ответ для примера $i$, $\hat{Y_i}$ - предсказание модели для примера $i$, $n$ - количество примеров в батче.

In [ ]:
class MSELoss:
    @typechecked
    def forward(self, y_pred: TensorType["batch"], y_true: TensorType["batch"]) -> Scalar:
        return # <реализовать логику MSE>

In [ ]:
y_pred = th.tensor([1.0, 3.0, 5.0])
y_true = th.tensor([2.0, 3.0, 4.0])

In [ ]:
from torchtyping import TensorType, patch_typeguard

patch_typeguard()
Scalar = TensorType[()]

class MSELoss:
    @typechecked
    def forward(self, y_pred: TensorType["batch"], y_true: TensorType["batch"]) -> Scalar:
        error = (y_pred - y_true)**2
        return th.mean(error)

In [ ]:
y_pred = th.tensor([1.0, 3.0, 5.0])
y_true = th.tensor([2.0, 3.0, 4.0])

mse_loss = MSELoss()
loss = mse_loss.forward(y_pred, y_true)

print(f"Предсказанные значения: {y_pred}")
print(f"Истинные значения: {y_true}")
print(f"MSE Loss: {loss}")

Предсказанные значения: tensor([1., 3., 5.])
Истинные значения: tensor([2., 3., 4.])
MSE Loss: 0.6666666865348816


## Задачи для самостоятельного решения

### Cоздание полносвязных слоев

<p class="task" id="1"></p>

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения) и опциональным вектором смещения.

$$y = xW^T + b$$

Пропустите вектор `inputs` через слой и выведите результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

- [ ] Проверено на семинаре

In [ ]:
#class Linear:
#    def __init__(self, n_neurons: int, n_features: int, bias: bool = False) -> None:
#        self.weights = th.randn(n_neurons, n_features)
#        self.bias = th.randn(n_neurons)
#
#    def forward(self, inputs: TensorType["batch", "feats"]) -> TensorType["batch", "n_neurons"]:
#        return th.mm(inputs, self.weights) # ["bath", "n_features"] * (n_features, n_neurons)

In [ ]:
class Linear:
    def __init__(self, n_features: int, n_neurons: int, bias: bool = False):
        self.weights = th.randn(n_neurons, n_features)
        self.bias = th.randn(n_neurons) if bias else th.zeros(n_neurons)

    def forward(self, inputs: TensorType["batch", "n_features"]) -> TensorType["batch", "n_neurons"]:
        return inputs @ self.weights.T + self.bias

In [ ]:
batch_size = 4
n_features = 5
n_neurons = 3

inputs = th.randn(batch_size, n_features)
linear_layer = Linear(n_features, n_neurons, bias=True)
output = linear_layer.forward(inputs)

print(f"Размер выхода слоя: {output.shape} (ожидаем: {batch_size, n_neurons})")

Размер выхода слоя: torch.Size([4, 3]) (ожидаем: (4, 3))


<p class="task" id="2"></p>

2\. Используя решение предыдущей задачи, создайте 2 полносвязных слоя и пропустите тензор `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выберите произвольно, количество нейронов во втором слое выберите так, чтобы результатом прогона являлась матрица `batch_size x 7`.

- [ ] Проверено на семинаре

In [ ]:
batch_size = 10
input_features = 20
inputs = th.randn(batch_size, input_features)

layer1 = Linear(n_features=input_features, n_neurons=15, bias=True)
layer2 = Linear(n_features=15, n_neurons=7, bias=True)

output1 = layer1.forward(inputs)
final_output = layer2.forward(output1)

print(f"Размер итогового выхода: {final_output.shape} (ожидаем: {batch_size, 7})")

Размер итогового выхода: torch.Size([10, 7]) (ожидаем: (10, 7))


### Создание функций активации

<p class="task" id="3"></p>

3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

$$\overrightarrow{x} = (x_1, ..., x_J)$$

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров. Функция должна применяться переданной на вход матрице построчно.

- [ ] Проверено на семинаре

In [ ]:
class Softmax:
    def forward(self, inputs: TensorType["batch", "feats"]) -> TensorType["batch", "feats"]:
        exps = th.exp(inputs)
        sum_exps = th.sum(exps, dim=1, keepdim=True)
        return exps / sum_exps

In [ ]:
softmax_activation = Softmax()
input_matrix = th.randn(4, 3)
output_matrix = softmax_activation.forward(input_matrix)
print(th.sum(output_matrix, dim=1))
print(output_matrix)

tensor([1.0000, 1.0000, 1.0000, 1.0000])
tensor([[0.1259, 0.6943, 0.1798],
        [0.5271, 0.0899, 0.3830],
        [0.2232, 0.6180, 0.1588],
        [0.4461, 0.2499, 0.3040]])


<p class="task" id="4"></p>

4 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создайте матрицу размера 4x3, заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

- [ ] Проверено на семинаре

In [ ]:
class ELU:
    def __init__(self, alpha: float = 1.0):
        self.alpha = alpha

    def forward(self, inputs: TensorType["batch", "feats"]) -> TensorType["batch", "feats"]:
        output = inputs.clone()
        neg_indices = inputs < 0
        output[neg_indices] = self.alpha * (th.exp(output[neg_indices]) - 1)
        return output

In [ ]:
elu_activation = ELU(alpha=1.0)
input_matrix = th.randn(4, 3)
output_matrix = elu_activation.forward(input_matrix)

print("Входная матрица:\n", input_matrix)
print("Матрица после ELU:\n", output_matrix)

Входная матрица:
 tensor([[ 0.4092,  2.3805,  1.5310],
        [ 0.0853,  1.9395, -0.9296],
        [-0.4913, -0.4839, -0.3274],
        [-0.4648, -0.3639,  0.8862]])
Матрица после ELU:
 tensor([[ 0.4092,  2.3805,  1.5310],
        [ 0.0853,  1.9395, -0.6053],
        [-0.3882, -0.3837, -0.2792],
        [-0.3717, -0.3050,  0.8862]])


### Создание функции потерь

<p class="task" id="5"></p>

5 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь CrossEntropyLoss:

$$y_i = (y_{i,1},...,y_{i,k})$$

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

$$ CrossEntropyLoss = \frac{1}{n}\sum_{i=1}^{n}{L_i}$$
где $y_i$ - вектор правильных ответов для примера $i$, $\hat{y_i}$ - вектор предсказаний модели для примера $i$; $k$ - количество классов, $n$ - количество примеров в батче.

Создайте полносвязный слой с 2 нейронами и прогнать через него батч `inputs`. Полученный результат пропустите через функцию активации Softmax. Посчитайте значение функции потерь, трактуя вектор `y` как вектор правильных ответов.

- [ ] Проверено на семинаре

In [ ]:
class CrossEntropyLoss:
    def forward(self, y_pred: TensorType["batch", "float"], y_true: TensorType["batch", "int"]) -> TensorType[()]:
        batch_size = y_pred.shape[0]

        correct_log_probs = th.log(y_pred[range(batch_size), y_true])
        loss = -th.mean(correct_log_probs)
        return loss

In [ ]:
batch_size = 4
n_features = 5
n_neurons = 3

inputs = th.randn(batch_size, n_features)
y_true = th.tensor([0, 2, 1, 1])

layer = Linear(n_features, n_neurons)
logits = layer.forward(inputs)
softmax = Softmax()
y_pred = softmax.forward(logits)

cross_entropy = CrossEntropyLoss()
loss = cross_entropy.forward(y_pred, y_true)
loss.item()

2.7213234901428223

<p class="task" id="6"></p>

6 Модифицируйте MSE, добавив L2-регуляризацию.

$$MSE_R = MSE + \lambda\sum_{i=1}^{m}w_i^2$$

где $\lambda$ - коэффициент регуляризации; $w_i$ - веса модели.

- [ ] Проверено на семинаре

In [ ]:
class MSERegularized:
    def __init__(self, lambda_: float):
        self.lambda_ = lambda_

    def data_loss(self, y_pred: TensorType["batch"], y_true: TensorType["batch"]) -> Scalar:
        return th.mean((y_pred - y_true) ** 2)

    def reg_loss(self, weights: TensorType) -> Scalar:
        return th.sum(weights ** 2)

    def forward(self, y_pred: TensorType["batch"], y_true: TensorType["batch"], weights: TensorType) -> Scalar:
        return self.data_loss(y_pred, y_true) + self.lambda_ * self.reg_loss(weights)

In [ ]:
weights = th.tensor([0.5, -1.2, 0.8, 2.1])

y_pred = th.tensor([1.5, 2.8])
y_true = th.tensor([1.0, 3.0])

lambda_ = 0.01

regularized_loss_func = MSERegularized(lambda_=lambda_)
total_loss = regularized_loss_func.forward(y_pred, y_true, weights)

mse = ((1.5-1.0)**2 + (2.8-3.0)**2) / 2
l2 = 0.5**2 + (-1.2)**2 + 0.8**2 + 2.1**2
expected_total_loss = mse + lambda_ * l2

print(f"MSE: {regularized_loss_func.data_loss(y_pred, y_true)}")
print(f"L2: {regularized_loss_func.reg_loss(weights)}")
print(f"Итог: {total_loss}")
print(f"Ожидание: {expected_total_loss}")

MSE: 0.14500001072883606
L2: 6.739999771118164
Итог: 0.21240000426769257
Ожидание: 0.21240000000000003
